fail_fast: true

repos:
  # Batch of helpful formatters and patterns
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements

  # Adds a standard feel to import segments, adds future annotations
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports
        args:
          - "--py36-plus"
          - "--application-directories"
          - ".:src"

  # Automatically upgrade syntax to newer versions
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args:
          - "--py36-plus"

  # Format code. No, I don't like everything black does either.
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - "src"
          - "tests"

  # Flake8 for linting, line-length adjusted to match Black default
  - repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-builtins
        args:
          - "src"
          - "tests"

  # Type enforcement for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          - "src"
          - "--exclude"
          - "src/click_repl/__init__.py"
