name: Format code

on:
  - push
  - pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install black isort autoflake

      - name: Format code with black
        run: |
          black src tests

      - name: Sort imports with isort
        run: |
          isort src tests

      - name: Remove unused imports with autoflake
        run: |
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Format code with black"
          add: "."
          branch: ${{ github.ref }}