name: black
on:
  push
  merge

jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python Environment
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install black
      - name: Run black
      - run: |
          black src tests