name: Tests

on:
  - push
  - pull_request

jobs:
  # Lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install -U pip
  #         pip install black flake8

  #     - name: Black Format Check
  #       run: |
  #         black --check src tests

  #     - name: Flake8 Lint Check
  #       run: |
  #         flake8 src tests

  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.11', '3.12', '3.13-dev', 'pypy-3.8', 'pypy-3.9']
        click-version: ['==7.1.2', '>=8.1']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install tox tox-gh-actions click${{ matrix.click-version }}
    - name: Test with tox
      run: tox

  # Refactor:
  #   needs: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install -U pip
  #         pip install black isort autoflake mypy ruff
  #     - name: Format code with black
  #       run: |
  #         black src tests
  #     - name: Sorts and Remove unused imports with isort
  #       run: |
  #         isort src tests
  #     - name: Remove unused variables with autoflake
  #       run: |
  #         autoflake --in-place --remove-unused-variables --recursive .
  #     - name: Linter
  #       run: |
  #         mypy src
  #         ruff src tests
  #     - name: Commit changes
  #       uses: EndBug/add-and-commit@v4
  #       with:
  #         author_name: ${{ github.actor }}
  #         author_email: ${{ github.actor }}@users.noreply.github.com
  #         message: "Refactored Code"
  #         add: "src"
  #         branch: ${{ github.ref }}
