name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', 'pypy-3.8', 'pypy-3.9']
        click-version: ['7.1.2', '8.1.2']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions click==${{ matrix.click-version }}
    - name: Test with tox
      run: tox

  py2_tests:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['2.7', 'pypy-2.7']
        click-version: ['6.7', '7.1.2']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        python -m pip install tox tox-gh-actions click==${{ matrix.click-version }}
    - name: Test with tox
      run: tox

  formatter:
    needs: [test, py2_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install black isort autoflake

      - name: Format code with black
        run: |
          black src tests

      - name: Sort imports with isort
        run: |
          isort src tests

      - name: Remove unused imports with autoflake
        run: |
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Format code with black"
          add: "src"
          branch: ${{ github.ref }}
